name: video_manipulation_example
description: Demonstrates how to use the video_manipulation plugin.
publish_to: 'none'

environment:
  sdk: ">=2.3.0-dev.0.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  video_player: 0.10.1+3
  path_provider: 1.1.0
  cupertino_icons: ^0.1.2

  flutter_ffmpeg: 0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  video_manipulation:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - assets/
